[unstable]
panic-abort-tests = true

[target.x86_64-unknown-none]
runner = "cargo run -p toru_os --bin qemu-test --"

[alias]
ktest = "test --target x86_64-unknown-none -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem -p kernel"