[unstable]
panic-abort-tests = true

[target.x86_64-unknown-none]
runner = "cargo run -p toru_os --bin qemu-test --"

[alias]
build-kernel = "build -p kernel --target x86_64-unknown-none -Zbuild-std=core,compiler_builtins,alloc -Zbuild-std-features=compiler-builtins-mem"
run-uefi = "run --bin qemu-uefi"
run-bios = "run --bin qemu-bios"

[build]
jobs = 8